export const surpriseMePrompts = [
  "a shoe in the shape of an avocado",
  "a surrealist dream-like oil painting by Salvador Dalí of a shoe playing checkers",
  "teddy bears shopping for shoes in Japan, ukiyo-e",
  "an oil painting by Matisse of a shoe playing chess",
  "panda mad scientist mixing sparkling shoe designs, digital art",
  "a macro 35mm photograph of shoes in Hawaii, designed with tiny surf boards, digital art",
  "3D render of shoes designed with a cute tropical fish on a dark blue background, digital art",
  "shoes for an astronaut lounging in a tropical resort in space, vaporwave",
  "an oil painting portrait of a shoe in medieval royal design and ornate patterns on a dark background",
  "a stained glass window depicting a shoe and french fries",
  "a pencil and watercolor drawing of a futuristic shoe with flying features",
  "shoes designed for a sunlit indoor lounge area with a pool with clear water and another pool with translucent pastel pink water, digital art",
  "a shoe designed for a fortune-telling shiba inu reading your fate in a giant hamburger, digital art",
  '"a shoe with a pearl earring" by Johannes Vermeer',
  "an oil pastel drawing of a shoe designed for an annoyed cat in a spaceship",
  "a shoe painting in the style of Starry Night",
  "a shoe that looks like a monster, knitted out of wool",
  "A plush toy shoe sitting against a yellow wall",
  "A shoe with a synthwave style sunset design, digital art",
  "Shoes for walking on a skybridge covered in lush foliage, digital art",
  "A 3D render of a shoe with a rainbow colored hot air balloon design",
  "A shoe with a comic book cover design of a superhero wearing headphones",
  "A shoe with a design of a centered explosion of colorful powder on a black background",
  "A shoe for a Samoyed dog with its tongue out hugging a white Siamese cat",
  "A shoe for a white fur monster standing in a purple room",
  "A shoe inspired by Michelangelo's sculpture of David wearing headphones djing",
  "A Samurai shoe for riding a Horse on Mars, lomography.",
  "A sleek shoe for driving a modern Cadillac along the Gardiner expressway with downtown Toronto in the background, 50mm photography",
  "A realistic photograph of a shoe for a young woman with blue eyes and blonde hair",
  "A shoe for standing in front of a stargate to another dimension",
  "Shoes for Spongebob Squarepants in the Blair Witch Project",
  "A shoe for a velociraptor working at a hotdog stand, lomography",
  "A shoe for a man walking through the bustling streets of Kowloon at night, lit by many bright neon shop signs, 50mm lens",
  "A shoe that looks like a living BBQ, in the style of a Pixar animated movie",
  "A shoe for a futuristic cyborg dance club, neon lights",
  "A shoe from the long-lost Star Wars 1990 Japanese Anime",
  "A shoe in the shape of a hamburger Rubik’s cube, professional food photography",
  "A Synthwave Hedgehog shoe, Blade Runner Cyberpunk",
  "A shoe for an astronaut encountering an alien life form on a distant planet, photography",
  "A shoe for a Dinosaur exploring Cape Town, photography",
  "A shoe for a Man falling in Love with his Computer, digital",
];
